export const GET_MOVIE = "GET_MOVIE"
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS"

export const GET_TV = "GET_TV"
export const GET_TV_SUCCESS = 'GET_TV_SUCCESS'

export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS'
export const GET_SEARCH_RESULTS_SUCCESS = 'GET_SEARCH_RESULTS_SUCCESS'