export const GET_DETAIL = 'GET_DETAIL'
export const GET_DETAIL_SUCCESS = 'GET_DETAIL_SUCCESS'

export const CLEAR_DATA_DETAIL = 'CLEAR_DATA_DETAIL'

export const GET_CAST = 'GET_CAST'
export const GET_CAST_SUCCESS = 'GET_CAST_SUCCESS'

export const GET_RECOMMENDATION = 'GET_RECOMMENDATION'
export const GET_RECOMMENDATION_SUCCESS = 'GET_RECOMMENDATION_SUCCESS'